homepage:
  path: /{_locale}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  requirements:
    _locale: '%app_locales%'
  defaults:
    template: lucky/number.html.twig
    _locale: '%locale%'

controllers:
  resource: ../src/Controller/
  type: attribute